name: Java CI with Gradle

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

  deploy:
    if: endswith(github.ref_name, 'master') && github.ref_type == 'branch'
    runs-on: ubuntu-latest
    env:
      APPVEYOR_BUILD_VERSION: '1.1.3'
      CURSETOKEN: ${{ secrets.CURSETOKEN }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Deploy
      uses: gradle/gradle-build-action@v2
      with:
        arguments: curseforge
